export const SIGHT_WORDS: string[] = [
    'am', 'at', 'can', 'go', 'is', 'like', 'me', 'see', 'the', 'to', 
    'dad', 'he', 'in', 'it', 'look', 'mom', 'my', 'on', 'up', 'we',
    'and', 'are', 'come', 'for', 'got', 'here', 'not', 'play', 'said', 'you',
    'day', 'down', 'into', 'looking', 'she', 'they', 'went', 'where', 'will', 'your',
    'all', 'away', 'back', 'big', 'her', 'over', 'this', 'want', 'who', 'with',
    'came', 'have', 'help', 'next', 'now', 'one', 'some', 'then', 'was', 'what'
];

export const SENTENCES: string[] = [
    "I can see the big mom.",
    "Look at my dad.",
    "We like to play here.",
    "She said, 'Come over here.'",
    "Where will you go now?",
    "He went into the big house.",
    "What was that one thing?",
    "They are looking for your help.",
    "I want some help with this.",
    "Who came back for me?",
    "You and I can play.",
    "Go up and see the dog.",
    "It is a fun day.",
    "My mom is not here.",
    "Dad will come down.",
    "She got on the bus.",
    "They went looking for it.",
    "I am your friend.",
    "I want to go with you.",
    "She will help now.",
    "He was next to her.",
    "We have a big dog.",
    "Then some birds flew away.",
    "Who will play this game?",
    "All of us want to go.",
    "Did you see my cat?",
    "I have a red ball.",
    "Come and play with me.",
    "This is my new toy.",
    "He will help you now.",
    "She went to the park.",
    "They want to eat now.",
    "What is your name?",
    "I like to read books.",
    "The dog is big and brown.",
    "We are going to the store.",
    "Look at the yellow sun.",
    "Where is the little mouse?",
    "Can you help me with this?",
    "I want one more cookie.",
    "She is my best friend.",
    "He got a new bike.",
    "Come here and sit down.",
    "I see a bird up in the tree.",
    "My dad is tall.",
    "Mom said it is time for bed.",
    "You are a good helper.",
    "I will go to school today.",
    "We went on a fun trip.",
    "The cat ran away from the dog."
];
